### ISSUE TITLE
Use of deprecated ElementTree method

### ISSUE THREAD

**Issue by walkerh** [hgsc-project-managers/ngsi-pm#14] opened 2019-04-30 15:16 UTC
In `test_ec20_xlsx_unit`.

"DeprecationWarning: The html argument of XMLParser() is deprecated"

Being called through the defusedxml third-party package.

**Comment by itsmarcy** [comment] 2019-04-30 18:27
openpyxl is using the deprecated method.
The issue is being tracked in their bitbucket repo [here](https://bitbucket.org/openpyxl/openpyxl/issues/1267/remove-deprecation-warning-from-defusedxml).
Because it's an openpyxl would a `@pytest.mark.filterwarnings` be sufficient for that one test case until openpyxl fixes the issue?

**Comment by itsmarcy** [comment] 2019-07-10 14:46
I am no longer able to reproduce the issue as before. I'm not certain as to why since it does not seem like openpyxl has resolved the issue. 
- Tested this in `master` with an updated conda environment and a specific environment that jw has, with no issue.
- Tested this in `hgv19_testing` with no DeprecatedWarning issue in both an updated environment and a specific environment.

Closing and will reopen if this manages to creep up again.

**Closed as completed by itsmarcy** 2019-07-10 14:46 UTC
Labels: bug
